name: Publish Org Secrets to Vault

on:
    push:
        branches:
            - main

jobs:
    publish_secrets:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Publish Org Secrets
              run: |
                # Crie um arquivo para armazenar os valores das secrets
                echo "Secret Values:" > secrets.txt

                echo "API_TOKEN_GITHUB=${{ secret.API_TOKEN_GITHUB }}" >> secrets.txt

                echo "AWS_ACCESS_KEY=${{ secret.AWS_ACCESS_KEY }}" >> secrets.txt

                echo "AWS_HOSTED_ZONE_ID=${{ secret.AWS_HOSTED_ZONE_ID }}" >> secrets.txt

                echo "AWS_REGION=${{ secret.AWS_REGION }}" >> secrets.txt

                echo "AWS_SECRET_KEY=${{ secret.AWS_SECRET_KEY }}" >> secrets.txt

                echo "DOCKER_PASSWORD=${{ secret.DOCKER_PASSWORD }}" >> secrets.txt

                echo "DOCKER_USERNAME=${{ secret.DOCKER_USERNAME }}" >> secrets.txt

                echo "DO_TOKEN=${{ secret.DO_TOKEN }}" >> secrets.txt

                echo "EMAIL_GITHUB=${{ secret.EMAIL_GITHUB }}" >> secrets.txt

                echo "GH_EMAIL=${{ secret.GH_EMAIL }}" >> secrets.txt

                echo "GH_USERNAME=${{ secret.GH_USERNAME }}" >> secrets.txt

                echo "GRAFANA_API_TOKEN=${{ secret.GRAFANA_API_TOKEN }}" >> secrets.txt

                echo "INFRACOST_API_KEY=${{ secret.INFRACOST_API_KEY }}" >> secrets.txt

                echo "KEYPAIR=${{ secret.KEYPAIR }}" >> secrets.txt

                echo "POSTGRES_PASSWORD=${{ secret.POSTGRES_PASSWORD }}" >> secrets.txt

                echo "USER_GITHUB=${{ secret.USER_GITHUB }}" >> secrets.txt

                echo "VAULT_TOKEN=${{ secret.VAULT_TOKEN }}" >> secrets.txt

            - name: Upload Secrets Artifact
              uses: actions/upload-artifact@v3
              with:
                name: org-secrets
                path: secrets.txt
