name: Publish Org Secrets to Vault

on:
    push:
        branches:
            - main

jobs:
    publish_secrets:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Publish Org Secrets
              run: |
                # Crie um arquivo para armazenar os valores das secrets
                echo "Secret Values:" > secrets.txt

                echo "API_TOKEN_GITHUB=${{ secrets.API_TOKEN_GITHUB }}" >> secrets.txt

                echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> secrets.txt

                echo "AWS_HOSTED_ZONE_ID=${{ secrets.AWS_HOSTED_ZONE_ID }}" >> secrets.txt

                echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> secrets.txt

                echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> secrets.txt

                echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> secrets.txt

                echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> secrets.txt

                echo "DO_TOKEN=${{ secrets.DO_TOKEN }}" >> secrets.txt

                echo "EMAIL_GITHUB=${{ secrets.EMAIL_GITHUB }}" >> secrets.txt

                echo "GH_EMAIL=${{ secrets.GH_EMAIL }}" >> secrets.txt

                echo "GH_USERNAME=${{ secrets.GH_USERNAME }}" >> secrets.txt

                echo "GRAFANA_API_TOKEN=${{ secrets.GRAFANA_API_TOKEN }}" >> secrets.txt

                echo "INFRACOST_API_KEY=${{ secrets.INFRACOST_API_KEY }}" >> secrets.txt

                echo "KEYPAIR=${{ secrets.KEYPAIR }}" >> secrets.txt

                echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> secrets.txt

                echo "USER_GITHUB=${{ secrets.USER_GITHUB }}" >> secrets.txt

                echo "VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}" >> secrets.txt

            - name: Upload Secrets Artifact
              uses: actions/upload-artifact@v3
              with:
                name: org-secrets
                path: secrets.txt
